---
name: "tenrev"
extractions:
    Inverter:
        type : "xml"
        # Optional 
        output: "/etc/password"
        series:
            pac:
                name: "Pac"
                orient: "row"
                row: 0
                # Optional
                cond:
                    name: "blabla"
                    orient: "row"
                    row: 1
        vector_value:
            date:
                orient: "column"
                index: 0
                from: 2
                # -1 means end of file
                to: -1
            time:
                orient: "column"
                index: 1
                from: 2
                # -1 means end of file
                to: -1
        single_value:
            date:
                orient:

structure:
    inverter:
        type: "filename"
        pattern: "(?P<NAME>.*?)_treated_data"
        src: "./tenrev/"
        child:
            mppt:
                type: "data"
                orient: "column"
                oth_axis_nth: 0
                pattern: "(?P<NAME>.*?)_mppt"
                child:
                    string:
                        type: "data"
                        orient: "column"
                        oth_axis_nth: 0
                        pattern: "(?P<PARENT>\\w+)(?P<NAME>\\d+)_string"
                        # pattern: "\\w+(\\d+)_string"
                        # parent:
                        #     pattern: "(?P<NAME>\\w+)\\d+_string"




