version: "3.3"

services:
  clang:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ../:/code
      # - data_pv:/code/parsing/core/tests/test_data/data_pv/

    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
    command: /bin/sh -c "while sleep 1000; do :; done"
