name: Build and Publish Docker Image

on:
    push:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   id: image_registry_lower
                uses: ASzc/change-string-case-action@v2
                with:
                    string: ghcr.io/${{ github.repository }}
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
                with:
                    driver: docker-container
                    driver-opts: |
                        image=moby/buildkit:master
                        network=host
            -   name: Log into registry ghcr.io
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.ACCESS_TOKEN }}

            -   name: Extract Docker metadata
                id: meta
                uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
                with:
                    github-token: ${{ secrets.ACCESS_TOKEN }}
                    images: ${{ steps.image_registry_lower.outputs.lowercase }}
                    tags: |
                        type=ref, event=branch
            -   name: Build and push Docker image
                uses: docker/build-push-action@v2
                id: build
                with:
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    file: docker/Dockerfile
                    cache-from: type=registry,ref=${{ steps.image_registry_lower.outputs.lowercase }}:buildcache-${{ github.ref_name }}
                    cache-to: type=registry,ref=${{ steps.image_registry_lower.outputs.lowercase }}:buildcache-${{ github.ref_name }},mode=max
