# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
    push:
        branches: [ master ]
#        paths:
#            - docker/*
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   id: image_registry_lower
                uses: ASzc/change-string-case-action@v2
                with:
                    string: ghcr.io/${{ github.repository }}
            # Set docker driver to permit cache
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
                with:
                    driver: docker-container
                    driver-opts: |
                        image=moby/buildkit:master
                        network=host
            # Login against a Docker registry except on PR
            # https://github.com/docker/login-action
            -   name: Log into registry ghcr.io
                uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            # Extract metadata (tags, labels) for Docker
            # https://github.com/docker/metadata-action
            -   name: Extract Docker metadata
                id: meta
                uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    images: ${{ steps.image_registry_lower.outputs.lowercase }}
                    tags: |
                        type=ref, event=branch
            # Build and push Docker image with Buildx (don't push on PR)
            # https://github.com/docker/build-push-action
            -   name: Build and push Docker image
                uses: docker/build-push-action@v2
                id: build
                with:
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    file: docker/Dockerfile
                    cache-from: type=registry,ref=${{ steps.image_registry_lower.outputs.lowercase }}:buildcache-${{ github.ref_name }}
                    cache-to: type=registry,ref=${{ steps.image_registry_lower.outputs.lowercase }}:buildcache-${{ github.ref_name }},mode=max
