
name: Test

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/sanoguzhan/refacto:master
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.ACCESS_TOKEN }}
        steps:
            -   uses: actions/checkout@v2
            -   name: Cpp Check
                run: |
                    cppcheck -i/pugixml.cpp --language=c++ --enable=all --xml --xml-version=2 parsing 2
            -   name: Build Refacto Tests
                run: |
                    ./parsing/core/cmd/build.sh 
            -   name: Cpp Library Test
                run: |
                    ./parsing/core/cmd/test.sh 