
name: test

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/feedgy/refacto:master
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        steps:
            -   uses: actions/checkout@v2
            -   name: Cpp Check
                run: |
                    cppcheck -i/pugixml.cpp --language=c++ --enable=all --xml --xml-version=2 parsing 2> cppcheck-result.xml
            -   name: Cpp Check
                run: |
                    cppcheck -i/pugixml.cpp --language=c++ --enable=all --xml --xml-version=2 parsing 2> cppcheck-result.xml
            -   name: Cpp Library Test
                run: |
                    ./parsing/core/cmd/test.sh 