
name: Test

on: [push, pull_request]

jobs:

    registry:
        runs-on: ubuntu-latest
        steps:
            -   id: image_registry_lower
                uses: ASzc/change-string-case-action@v2
                with:
                    string: ghcr.io/${{ github.repository }}
        outputs:
          name: ${{ steps.image_registry_lower.outputs.lowercase }}
    test:
        runs-on: ubuntu-latest
        needs: [registry]
        container:
            image: ghcr.io/${{ needs.registry.outputs.name }}:master
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.ACCESS_TOKEN }}
        steps:
        
            -   uses: actions/checkout@v2
            -   name: Create Build Directory 
                run: |
                    cd .. && mkdir build
            -   name: Build Project 
                run: |
                     cmake . -B build && cmake --build . --target install 
            -   name: Run Tests
                run: |
                    ctest -C Release
