name: Release

on: 
  push:
    branches: [ staging, production ]

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
      new_version: ${{ steps.tag.outputs.new_version }}
      changelog: ${{ steps.tag.outputs.changelog }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  versioning:
    runs-on: ubuntu-latest
    needs: tag
    outputs: 
      version : ${{ steps.service_url.outputs.value}}
    steps:
      - name: Patch service url
        uses: haya14busa/action-cond@v1
        id: service_url
        with:
          cond: ${{ github.ref_name == 'staging'}}
          if_true:  '${{ needs.tag.outputs.new_version }}.dev'
          if_false: ${{ needs.tag.outputs.new_version }}

  build: 
    needs: versioning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set version
      run: |
        echo "::set-env name=LIB_VERSION::${{ needs.versioning.outputs.version }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Build packages
      run: |
        pip install -U twine wheel
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: parsing
        path: dist/*