name: Release

on: 
  push:
    branches: [ staging, production ]

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
      new_version: ${{ steps.tag.outputs.new_version }}
      changelog: ${{ steps.tag.outputs.changelog }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  versioning:
    runs-on: ubuntu-latest
    needs: tag
    outputs: 
      version : ${{ steps.service_url.outputs.value}}
    steps:
      - name: Fix versioning
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ github.ref_name == 'staging'}}
          if_true:  '${{ needs.tag.outputs.new_version }}.dev'
          if_false: ${{ needs.tag.outputs.new_version }}

  deploy-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - tag
    outputs:
      pushed_tag: ${{needs.tag.outputs.new_tag}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: image_registry_lower
        uses: ASzc/change-string-case-action@v2
        with:
          string: ghcr.io/${{ github.repository }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
            network=host
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
   

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: ${{ steps.image_registry_lower.outputs.lowercase }}
          tags: |
            type=semver, pattern={{raw}}, value=${{needs.tag.outputs.new_tag}}
            type=ref, event=branch
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        id: build
        with:
          context: ..
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/Dockerfile
          cache-from: type=registry,ref=${{ steps.image_registry_lower.outputs.lowercase }}:buildcache-${GITHUB_REF##*/}
          cache-to: type=registry,ref=${{ steps.image_registry_lower.outputs.lowercase }}:buildcache-${GITHUB_REF##*/},mode=max

  build: 
    needs: [ tag, versioning, deploy-docker] 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set version
      run: |
        echo "LIB_VERSION=${{ needs.versioning.outputs.version }}" >> $GITHUB_ENV
    - name: Change Log
      run: |
        echo '${{ needs.tag.outputs.changelog }}' | cat - docs/versions.md > temp && mv temp docs/versions.md
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Build packages
      run: |
        pip install -U twine wheel
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: parsing
        path: dist/*